"""empty message

Revision ID: c24ac2a54834
Revises: 177f22aa6a17
Create Date: 2020-01-24 15:10:09.325548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24ac2a54834'
down_revision = '177f22aa6a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'department')
    # ### end Alembic commands ###
